# enable the API
api: 
  # Dashboard
  #
  # Optional
  # Default: true
  # TODO: secure the dashboard 
  dashboard: true
  insecure: true

# enable ping
ping: {}

# define routers for http and set static rules
http:
  routers:
    redctf:
      service: "red-ctf"

    api:
      rule: PathPrefix(`/api`) || PathPrefix(`/dashboard`)
      service: api@internal


## Static configuration for entrypoints
entryPoints:
  red-ctf:
    address: ":80"
    proxyProtocol:
      insecure: true

  red-ctf-secure:
    address: ":443"
    proxyProtocol:
      insecure: true

  traefik:
    address: ":9090"
    proxyProtocol:
      insecure: true

# enable docker provider
providers:
  docker: 
    endpoint: "unix:///var/run/docker.sock"
    
    # if false exposed containers must have the traefik.enable=true label
    # exposedByDefault: false
    
    network: "traefik"
    
    # TODO: pass this in from the start up script
    domain: "red-ctf.woodnbottle.com"
    
    # TODO: configure secure connection to TLS docker socket
    # tls:
      # ca: path/to/ca.crt

    # Traefik routes requests to the IP/Port of the matching container.
    # TODO: is this necessary? its copied from the old traefik.toml file
    useBindPortIP: true
